---
title: "Swissmetro 2 - 500 draws BFGS "
output: html_document
date: "2024-04-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In the swissmetro 2 case, we have this time **4 random components** : time, cost, and error in the ASCs for train and car.


```{r library and settings}

### Clear memory
rm(list = ls())

### Load Apollo library
library(apollo)


#load dplyr library
library(dplyr)

#library to export coefficient in excel table
library(openxlsx)

### Initialise code
apollo_initialise()

### Set core controls
apollo_control = list(
  modelName       = "Swissmetro",
  modelDescr      = "Mixed logit model on Swissmetro, uncorrelated Lognormals in preference space",
  indivID         = "ID",  
  nCores          = 4,
  outputDirectory = "output"
)


```


## LOAD DATA

```{r}

file_path <- "C:/Users/alexi/Desktop/GITS/Semester-project/Data/swissmetro.dat"
  
db_swissmetro = read.table(file_path, header = TRUE)

exclude <- with(db_swissmetro, ((db_swissmetro$PURPOSE != 1) * (db_swissmetro$PURPOSE != 3) + (db_swissmetro$CHOICE == 0)) > 0)


db_swissmetro <- subset(db_swissmetro, !exclude) #This makes us go from  10,728 observations (rows) to 6,768



```


## DEFINING NEW VARIABLES

```{r}


#We define the new variables that we will use later and add them directly to the database


db_swissmetro$SM_COST <- db_swissmetro$SM_CO * (db_swissmetro$GA == 0)
db_swissmetro$TRAIN_COST <- db_swissmetro$TRAIN_CO * (db_swissmetro$GA == 0)
db_swissmetro$CAR_AV_SP <- db_swissmetro$CAR_AV * (db_swissmetro$SP != 0)
db_swissmetro$TRAIN_AV_SP <- db_swissmetro$TRAIN_AV * (db_swissmetro$SP != 0)
db_swissmetro$TRAIN_TT_SCALED <- db_swissmetro$TRAIN_TT / 100
db_swissmetro$TRAIN_COST_SCALED <- db_swissmetro$TRAIN_COST / 100
db_swissmetro$SM_TT_SCALED <- db_swissmetro$SM_TT / 100
db_swissmetro$CAR_TT_SCALED<- db_swissmetro$CAR_TT / 100
db_swissmetro$CAR_CO_SCALED <- db_swissmetro$CAR_CO / 100
db_swissmetro$SM_COST_SCALED <- db_swissmetro$SM_COST / 100 #idk why it doesnt rescale the SM_COST when exluding some of the data

#This makes us go from  28 variables (columns) to 38


```

```{r}

### Vector of parameters, including any that are kept fixed in estimation
apollo_beta = c(ASC_CAR        = 0,
                ASC_TRAIN      = 0,
                ASC_SM         = 0,
                B_COST         = 0,
                B_COST_S       = 1,
                B_TIME         = 0,
                B_TIME_S       = 1,
                SIGMA_1        = 1,
                SIGMA_2        = 1)

### Vector with names (in quotes) of parameters to be kept fixed at their starting value in apollo_beta, use apollo_beta_fixed = c() if none

apollo_fixed = c("ASC_SM")

```

## DEFINING RANDOM PARAMETERS

```{r}
set.seed(1)

### Set parameters for generating draws
apollo_draws = list(
  interDrawsType = "halton", #differences btw individuals
  interNDraws    = 500,
  interUnifDraws = c(),
  interNormDraws = c("draws_c", "draws_t", "draws_1", "draws_2"),  #Standard Normal dist draws
  intraDrawsType = "halton",
  intraNDraws    = 0,
  intraUnifDraws = c(),
  intraNormDraws = c()
)

### Create random parameters
apollo_randCoeff = function(apollo_beta, apollo_inputs){
  randcoeff = list()


  randcoeff[["B_COST_RND"]] = B_COST + B_COST_S * draws_c
  randcoeff[["B_TIME_RND"]] = B_TIME + B_TIME_S * draws_t
  randcoeff[["SIGMA_CAR_RND"]] = SIGMA_1 * draws_1
  randcoeff[["SIGMA_SM_RND"]] = SIGMA_2 * draws_2

  return(randcoeff)
}


```

### GROUP AND VALIDATE INPUTS

```{r}

apollo_inputs = apollo_validateInputs(database = db_swissmetro) #have to specify the name of the database, as it is by default called "database"

```

### DEFINE MODEL AND LIKELIHOOD FUNCTION

```{r}
apollo_probabilities=function(apollo_beta, apollo_inputs, functionality="estimate"){

  ### Function initialisation: do not change the following three commands
  ### Attach inputs and detach after function exit
  apollo_attach(apollo_beta, apollo_inputs)
  on.exit(apollo_detach(apollo_beta, apollo_inputs))

  ### Create list of probabilities P
  P = list()

  ### List of utilities: these must use the same names as in mnl_settings, order is irrelevant
  V = list()
  V[["alt1"]] = ASC_TRAIN + B_TIME_RND * TRAIN_TT_SCALED + B_COST_RND * TRAIN_COST_SCALED + SIGMA_CAR_RND
  V[["alt2"]] = ASC_SM + B_TIME_RND * SM_TT_SCALED + B_COST_RND * SM_COST_SCALED + SIGMA_SM_RND
  V[["alt3"]] = ASC_CAR + B_TIME_RND * CAR_TT_SCALED + B_COST_RND * CAR_CO_SCALED


  ### Define settings for MNL model component
  mnl_settings = list(
    alternatives  = c(alt1=1, alt2=2, alt3=3),
    avail         = list(alt1=TRAIN_AV_SP, alt2=SM_AV, alt3=CAR_AV_SP),
    choiceVar     = CHOICE,
    utilities     = V
  )

  ### Compute probabilities using MNL model
  P[["model"]] = apollo_mnl(mnl_settings, functionality)
  
    ### Take product across observation for same individual
  P = apollo_panelProd(P, apollo_inputs, functionality)

  ### Average across inter-individual draws
  P = apollo_avgInterDraws(P, apollo_inputs, functionality)


  ### Prepare and return outputs of function
  P = apollo_prepareProb(P, apollo_inputs, functionality)
  return(P)
}

```

### MODEL ESTIMATION

```{r}

estimate_settings = list(
    estimationRoutine  = "BFGS"
)


model = apollo_estimate(apollo_beta, apollo_fixed,apollo_probabilities, apollo_inputs, estimate_settings)

#unconditionals <- apollo_unconditionals(model, apollo_probabilities, apollo_inputs) #actual values used for random coefficients, want to import them as a excel table




```

### MODEL OUTPUTS

```{r}


apollo_modelOutput(model) #(FORMATTED OUTPUT (TO SCREEN))

apollo_saveOutput(model) #(FORMATTED OUTPUT (TO FILE, using model name))
```

