---
title: "CPU/RAM curves"
output: html_document
date: "2024-03-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Preparing the data:

```{r}
# Load required libraries
library(ggplot2)

# Read the CSV file
data_apollo <- read.csv("C:\\Users\\alexi\\Desktop\\GITS\\Semester-project\\Code\\cpu_ram_usage_apollo.csv")
colnames(data_apollo) <- c("Time", "CPU", "RAM")

# Read the CSV file
data_biogeme <- read.csv("C:\\Users\\alexi\\Desktop\\GITS\\Semester-project\\Code\\cpu_ram_usage_biogeme.csv")
colnames(data_biogeme) <- c("Time", "CPU", "RAM")
```

Plotting for Apollo:

```{r} 

# Plot using ggplot2
ggplot(data_apollo, aes(x = Time, group = 1)) +
  geom_line(aes(y = CPU, color = "CPU")) +
  geom_line(aes(y = RAM, color = "RAM")) +
  labs(x = "Time Passed (seconds)", y = "Usage (%)", color = "Metric") +
  scale_color_manual(values = c("CPU" = "red", "RAM" = "blue")) +
  ggtitle("CPU and RAM Usage Over Time") +
  theme_minimal()

```


Plotting for Biogeme:

```{r} 

# Plot using ggplot2
ggplot(data_biogeme, aes(x = Time, group = 1)) +
  geom_line(aes(y = CPU, color = "CPU")) +
  geom_line(aes(y = RAM, color = "RAM")) +
  labs(x = "Time Passed (seconds)", y = "Usage (%)", color = "Metric") +
  scale_color_manual(values = c("CPU" = "red", "RAM" = "blue")) +
  ggtitle("CPU and RAM Usage Over Time") +
  theme_minimal()

```

